# Generated by Django 3.2.6 on 2021-09-29 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='dicription',
            new_name='discription',
        ),
    ]
