# Generated by Django 3.2.7 on 2021-10-02 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchlist_app', '0008_alter_watchlist_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='review_user',
        ),
        migrations.AddField(
            model_name='review',
            name='review_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to='auth.user'),
            preserve_default=False,
        ),
    ]
